export default {
  LOGIN_LOADING: "LOGIN_LOADING",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  GETINFO_LOADING: "GETINFO_LOADING",
  GETINFO_SUCCESS: "GETINFO_SUCCESS",
  GETINFO_FAIL: "GETINFO_FAIL",

  LOGOUT_LOADING: "LOGOUT_LOADING",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAIL: "LOGOUT_FAIL",
};
