export const USER_LOGIN_REQUESTED = "USER_LOGIN_REQUESTED";
export const USER_LOGIN_SUCCEEDED = "USER_LOGIN_SUCCEEDED";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_INFO_RETRIEVE_REQUESTED = "USER_INFO_RETRIEVE_REQUESTED";
export const USER_INFO_RETRIEVE_SUCCEEDED = "USER_INFO_RETRIEVE_SUCCEEDED";
export const USER_INFO_RETRIEVE_FAILED = "USER_INFO_RETRIEVE_FAILED";

export const GET_LIST_OF_CATEGORIES_REQUESTED = "GET_LIST_OF_CATEGORIES_REQUESTED";
export const GET_LIST_OF_CATEGORIES_SUCCEEDED = "GET_LIST_OF_CATEGORIES_SUCCEEDED";
export const GET_LIST_OF_CATEGORIES_FAILED = "GET_LIST_OF_CATEGORIES_FAILED";

export const DELETE_CATEGORY_REQUESTED = "DELETE_CATEGORY_REQUESTED";
export const DELETE_CATEGORY_SUCCEEDED = "DELETE_CATEGORY_SUCCEEDED";
export const DELETE_CATEGORY_FAILED = "DELETE_CATEGORY_FAILED";
