export const USER_LOGIN_REQUESTED = "USER_LOGIN_REQUESTED";
export const USER_LOGIN_SUCCEEDED = "USER_LOGIN_SUCCEEDED";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_INFO_RETRIEVE_REQUESTED = "USER_INFO_RETRIEVE_REQUESTED";
export const USER_INFO_RETRIEVE_SUCCEEDED = "USER_INFO_RETRIEVE_SUCCEEDED";
export const USER_INFO_RETRIEVE_FAILED = "USER_INFO_RETRIEVE_FAILED";
