export const USER_LOGIN_REQUESTED = "USER_LOGIN_REQUESTED";
export const USER_LOGIN_SUCCEEDED = "USER_LOGIN_SUCCEEDED";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_INFO_RETRIEVE_REQUESTED = "USER_INFO_RETRIEVE_REQUESTED";
export const USER_INFO_RETRIEVE_SUCCEEDED = "USER_INFO_RETRIEVE_SUCCEEDED";
export const USER_INFO_RETRIEVE_FAILED = "USER_INFO_RETRIEVE_FAILED";

export const GET_LIST_OF_CATEGORIES_REQUESTED = "GET_LIST_OF_CATEGORIES_REQUESTED";
export const GET_LIST_OF_CATEGORIES_SUCCEEDED = "GET_LIST_OF_CATEGORIES_SUCCEEDED";
export const GET_LIST_OF_CATEGORIES_FAILED = "GET_LIST_OF_CATEGORIES_FAILED";

export const READ_CATEGORY_REQUESTED = "READ_CATEGORY_REQUESTED";
export const READ_CATEGORY_SUCCEEDED = "READ_CATEGORY_SUCCEEDED";
export const READ_CATEGORY_FAILED = "READ_CATEGORY_FAILED";

export const ADD_CATEGORY_REQUESTED = "ADD_CATEGORY_REQUESTED";
export const ADD_CATEGORY_SUCCEEDED = "ADD_CATEGORY_SUCCEEDED";
export const ADD_CATEGORY_FAILED = "ADD_CATEGORY_FAILED";

export const UPDATE_CATEGORY_REQUESTED = "UPDATE_CATEGORY_REQUESTED";
export const UPDATE_CATEGORY_SUCCEEDED = "UPDATE_CATEGORY_SUCCEEDED";
export const UPDATE_CATEGORY_FAILED = "UPDATE_CATEGORY_FAILED";

export const DELETE_CATEGORY_REQUESTED = "DELETE_CATEGORY_REQUESTED";
export const DELETE_CATEGORY_SUCCEEDED = "DELETE_CATEGORY_SUCCEEDED";
export const DELETE_CATEGORY_FAILED = "DELETE_CATEGORY_FAILED";

export const SET_ITEM_ID_REQUESTED = "SET_ITEM_ID_REQUESTED";
export const SET_ITEM_ID_SUCCEEDED = "SET_ITEM_ID_SUCCEEDED";
export const SET_ITEM_ID_FAILED = "SET_ITEM_ID_FAILED";

export const REMOVE_ITEM_ID_REQUESTED = "REMOVE_ITEM_ID_REQUESTED";
export const REMOVE_ITEM_ID_SUCCEEDED = "REMOVE_ITEM_ID_SUCCEEDED";
export const REMOVE_ITEM_ID_FAILED = "REMOVE_ITEM_ID_FAILED";

export const SET_PAGE_REQUESTED = "SET_PAGE_REQUESTED";
export const SET_PAGE_SUCCEEDED = "SET_PAGE_SUCCEEDED";
export const SET_PAGE_FAILED = "SET_PAGE_FAILED";

export const SET_ROWS_PER_PAGE_REQUESTED = "SET_ROWS_PER_PAGE_REQUESTED";
export const SET_ROWS_PER_PAGE_SUCCEEDED = "SET_ROWS_PER_PAGE_SUCCEEDED";
export const SET_ROWS_PER_PAGE_FAILED = "SET_ROWS_PER_PAGE_FAILED";

export const SET_SEARCH_VAL_REQUESTED = "SET_SEARCH_VAL_REQUESTED";
export const SET_SEARCH_VAL_SUCCEEDED = "SET_SEARCH_VAL_SUCCEEDED";
export const SET_SEARCH_VAL_FAILED = "SET_SEARCH_VAL_FAILED";

export const SHOW_MODAL_REQUESTED = "SHOW_MODAL_REQUESTED";
export const SHOW_MODAL_SUCCEEDED = "SHOW_MODAL_SUCCEEDED";
export const SHOW_MODAL_FAILED = "SHOW_MODAL_FAILED";

export const GET_LIST_OF_MODELTYPE_REQUESTED = "GET_LIST_OF_MODELTYPE_REQUESTED";
export const GET_LIST_OF_MODELTYPE_SUCCEEDED = "GET_LIST_OF_MODELTYPE_SUCCEEDED";
export const GET_LIST_OF_MODELTYPE_FAILED = "GET_LIST_OF_MODELTYPE_FAILED";

export const GET_LIST_OF_MODELTYPEPARAM_REQUESTED = "GET_LIST_OF_MODELTYPEPARAM_REQUESTED";
export const GET_LIST_OF_MODELTYPEPARAM_SUCCEEDED = "GET_LIST_OF_MODELTYPEPARAM_SUCCEEDED";
export const GET_LIST_OF_MODELTYPEPARAM_FAILED = "GET_LIST_OF_MODELTYPEPARAM_FAILED";

export const GET_LIST_OF_MODELTYPEINFO_REQUESTED = "GET_LIST_OF_MODELTYPEINFO_REQUESTED";
export const GET_LIST_OF_MODELTYPEINFO_SUCCEEDED = "GET_LIST_OF_MODELTYPEINFO_SUCCEEDED";
export const GET_LIST_OF_MODELTYPEINFO_FAILED = "GET_LIST_OF_MODELTYPEINFO_FAILED";

export const READ_MODELTYPEINFO_REQUESTED = "READ_MODELTYPEINFO_REQUESTED";
export const READ_MODELTYPEINFO_SUCCEEDED = "READ_MODELTYPEINFO_SUCCEEDED";
export const READ_MODELTYPEINFO_FAILED = "READ_MODELTYPEINFO_FAILED";

export const ADD_MODELTYPEINFO_REQUESTED = "ADD_MODELTYPEINFO_REQUESTED";
export const ADD_MODELTYPEINFO_SUCCEEDED = "ADD_MODELTYPEINFO_SUCCEEDED";
export const ADD_MODELTYPEINFO_FAILED = "ADD_MODELTYPEINFO_FAILED";

export const UPDATE_MODELTYPEINFO_REQUESTED = "UPDATE_MODELTYPEINFO_REQUESTED";
export const UPDATE_MODELTYPEINFO_SUCCEEDED = "UPDATE_MODELTYPEINFO_SUCCEEDED";
export const UPDATE_MODELTYPEINFO_FAILED = "UPDATE_MODELTYPEINFO_FAILED";

export const DELETE_MODELTYPEINFO_REQUESTED = "DELETE_MODELTYPEINFO_REQUESTED";
export const DELETE_MODELTYPEINFO_SUCCEEDED = "DELETE_MODELTYPEINFO_SUCCEEDED";
export const DELETE_MODELTYPEINFO_FAILED = "DELETE_MODELTYPEINFO_FAILED";
